bump_version: null
lint:
  nextflow_config:
    - config_defaults:
        - params.ribo_database_manifest
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Avani Bhojwani and Timothy Little
  description: A pipeline for de novo transcriptome assembly of short reads from bulk
    RNA-seq
  force: false
  is_nfcore: true
  name: denovotranscript
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.2.0dev
update: null
